# Generated by Django 3.0.7 on 2020-07-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recaudo',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('i', models.IntegerField()),
                ('ieb', models.IntegerField()),
                ('ii', models.IntegerField()),
                ('iii', models.IntegerField()),
                ('iv', models.IntegerField()),
                ('v', models.IntegerField()),
                ('eg', models.IntegerField()),
                ('er', models.IntegerField()),
                ('ea', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarifas',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('i', models.IntegerField()),
                ('ieb', models.IntegerField()),
                ('ii', models.IntegerField()),
                ('iii', models.IntegerField()),
                ('iv', models.IntegerField()),
                ('v', models.IntegerField()),
                ('eg', models.IntegerField()),
                ('er', models.IntegerField()),
                ('ea', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('i', models.IntegerField()),
                ('ieb', models.IntegerField()),
                ('ii', models.IntegerField()),
                ('iii', models.IntegerField()),
                ('iv', models.IntegerField()),
                ('v', models.IntegerField()),
                ('eg', models.IntegerField()),
                ('er', models.IntegerField()),
                ('ea', models.IntegerField()),
                ('pagaron', models.IntegerField()),
                ('evasores', models.IntegerField()),
                ('exentos', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
