# Generated by Django 3.0.7 on 2020-07-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exentos',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('i', models.IntegerField(default='NO')),
                ('ieb', models.IntegerField(default='NO')),
                ('ii', models.IntegerField(default='NO')),
                ('iii', models.IntegerField(default='NO')),
                ('iv', models.IntegerField(default='NO')),
                ('v', models.IntegerField(default='NO')),
                ('eg', models.IntegerField(default='NO')),
                ('er', models.IntegerField(default='NO')),
                ('ea', models.IntegerField(default='NO')),
            ],
        ),
    ]
