# Generated by Django 3.0.7 on 2020-07-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exentos',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('i', models.TextField(default='NO')),
                ('ieb', models.TextField(default='NO')),
                ('ii', models.TextField(default='NO')),
                ('iii', models.TextField(default='NO')),
                ('iv', models.TextField(default='NO')),
                ('v', models.TextField(default='NO')),
                ('eg', models.TextField(default='NO')),
                ('er', models.TextField(default='NO')),
                ('ea', models.TextField(default='NO')),
            ],
        ),
    ]
