# Generated by Django 3.0.7 on 2020-07-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_exentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='evasores',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='exentos',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='pagaron',
        ),
    ]
