# Generated by Django 3.0.7 on 2020-11-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rec_ideal_aguas_negras_rec_ideal_arcabuco_rec_ideal_bicentenario_rec_ideal_cano_rec_ideal_carimagua_'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Peajes',
        ),
    ]
