# Generated by Django 3.0.7 on 2020-07-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200716_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='recaudo_real',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('i', models.IntegerField()),
                ('ieb', models.IntegerField()),
                ('ii', models.IntegerField()),
                ('iii', models.IntegerField()),
                ('iv', models.IntegerField()),
                ('v', models.IntegerField()),
                ('eg', models.IntegerField()),
                ('er', models.IntegerField()),
                ('ea', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
