# Generated by Django 3.0.7 on 2020-08-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_recaudo_real'),
    ]

    operations = [
        migrations.CreateModel(
            name='rec_Gamarra',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('i', models.IntegerField()),
                ('ieb', models.IntegerField()),
                ('ii', models.IntegerField()),
                ('iii', models.IntegerField()),
                ('iv', models.IntegerField()),
                ('v', models.IntegerField()),
                ('eg', models.IntegerField()),
                ('er', models.IntegerField()),
                ('ea', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rec_ideal_Gamarra',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('i', models.IntegerField()),
                ('ieb', models.IntegerField()),
                ('ii', models.IntegerField()),
                ('iii', models.IntegerField()),
                ('iv', models.IntegerField()),
                ('v', models.IntegerField()),
                ('eg', models.IntegerField()),
                ('er', models.IntegerField()),
                ('ea', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rec_ideal_Santa_Ana',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('i', models.IntegerField()),
                ('ieb', models.IntegerField()),
                ('ii', models.IntegerField()),
                ('iii', models.IntegerField()),
                ('iv', models.IntegerField()),
                ('v', models.IntegerField()),
                ('eg', models.IntegerField()),
                ('er', models.IntegerField()),
                ('ea', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rec_Santa_Ana',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('i', models.IntegerField()),
                ('ieb', models.IntegerField()),
                ('ii', models.IntegerField()),
                ('iii', models.IntegerField()),
                ('iv', models.IntegerField()),
                ('v', models.IntegerField()),
                ('eg', models.IntegerField()),
                ('er', models.IntegerField()),
                ('ea', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='veh_Gamarra',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('i', models.IntegerField()),
                ('ieb', models.IntegerField()),
                ('ii', models.IntegerField()),
                ('iii', models.IntegerField()),
                ('iv', models.IntegerField()),
                ('v', models.IntegerField()),
                ('eg', models.IntegerField()),
                ('er', models.IntegerField()),
                ('ea', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='veh_Santa_Ana',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('i', models.IntegerField()),
                ('ieb', models.IntegerField()),
                ('ii', models.IntegerField()),
                ('iii', models.IntegerField()),
                ('iv', models.IntegerField()),
                ('v', models.IntegerField()),
                ('eg', models.IntegerField()),
                ('er', models.IntegerField()),
                ('ea', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
