# Generated by Django 3.0.7 on 2020-11-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_peajes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Peajes',
        ),
    ]
