# Generated by Django 3.0.7 on 2020-11-26 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_peajes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peajes',
            name='sentido',
        ),
    ]
