# Generated by Django 3.0.7 on 2020-10-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rec_aguas_negras_rec_casablanca_rec_cencar_rec_cerritos_rec_ciat_rec_cocorna_santuario_rec_curm_rec_'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peaje', models.TextField()),
                ('codigo', models.TextField()),
                ('pr', models.TextField()),
                ('distancia', models.TextField()),
                ('administra', models.TextField()),
                ('territorial', models.TextField()),
                ('sector', models.TextField()),
                ('ubicacion', models.TextField()),
            ],
        ),
    ]
